// lazyverilog benchmark filelist for hpc60
// 60 modules, each `include`-ing one large shared params.svh header
// models the shape of an original HPC batch-node startup report (see PERF_COMP.md)

+incdir+.
hpc_block_0.sv
hpc_block_1.sv
hpc_block_2.sv
hpc_block_3.sv
hpc_block_4.sv
hpc_block_5.sv
hpc_block_6.sv
hpc_block_7.sv
hpc_block_8.sv
hpc_block_9.sv
hpc_block_10.sv
hpc_block_11.sv
hpc_block_12.sv
hpc_block_13.sv
hpc_block_14.sv
hpc_block_15.sv
hpc_block_16.sv
hpc_block_17.sv
hpc_block_18.sv
hpc_block_19.sv
hpc_block_20.sv
hpc_block_21.sv
hpc_block_22.sv
hpc_block_23.sv
hpc_block_24.sv
hpc_block_25.sv
hpc_block_26.sv
hpc_block_27.sv
hpc_block_28.sv
hpc_block_29.sv
hpc_block_30.sv
hpc_block_31.sv
hpc_block_32.sv
hpc_block_33.sv
hpc_block_34.sv
hpc_block_35.sv
hpc_block_36.sv
hpc_block_37.sv
hpc_block_38.sv
hpc_block_39.sv
hpc_block_40.sv
hpc_block_41.sv
hpc_block_42.sv
hpc_block_43.sv
hpc_block_44.sv
hpc_block_45.sv
hpc_block_46.sv
hpc_block_47.sv
hpc_block_48.sv
hpc_block_49.sv
hpc_block_50.sv
hpc_block_51.sv
hpc_block_52.sv
hpc_block_53.sv
hpc_block_54.sv
hpc_block_55.sv
hpc_block_56.sv
hpc_block_57.sv
hpc_block_58.sv
hpc_block_59.sv
