./memory.sv
./xdef_lib.sv
./memory_top.sv
./folding_demo.sv
./demo.sv
./cell.sv
./inv.sv
./params.svh
+incdir+./uvm-core/src
./uvm-core/src/uvm_pkg.sv
./uvm_completion_demo.sv
./uvm_autocomplete_test.sv
./pkt_base.sv
./pkt_child.sv
./common_pkg.sv
./pkg_use.sv

+incdir+../tests/rtl/opentitan/hw/ip/prim/rtl
../tests/rtl/opentitan/hw/ip/uart/rtl/uart_reg_pkg.sv
../tests/rtl/opentitan/hw/ip/uart/rtl/uart_tx.sv
../tests/rtl/opentitan/hw/ip/uart/rtl/uart_rx.sv
../tests/rtl/opentitan/hw/ip/prim/rtl/prim_fifo_sync.sv
../tests/rtl/opentitan/hw/ip/prim_generic/rtl/prim_flop_2sync.sv
../tests/rtl/opentitan/hw/ip/prim/rtl/prim_intr_hw.sv
./uart_core.sv

../tests/rtl/opentitan/hw/ip/tlul/rtl/tlul_pkg.sv
../tests/rtl/opentitan/hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv
../tests/rtl/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_pkg.sv
../tests/rtl/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_reg_pkg.sv
../tests/rtl/opentitan/hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
../tests/rtl/opentitan/hw/ip/spi_device/rtl/spi_device_pkg.sv
./alert_handler_reg_top.sv
./pinmux_reg_top.sv
./spi_device.sv
