#!/usr/bin/env bash
# Launch Neovim in a completely isolated profile for testing the public
# LazyVerilog installation path documented in README.md.
#
# Why this script exists:
#   Developers often have a real ~/.config/nvim with many plugins, autocmds,
#   LSP settings, and cached state.  That environment is useful for daily work
#   but bad for release testing: a preinstalled local plugin, old server binary,
#   or custom LSP setup can hide installation bugs.  This script redirects all
#   Neovim XDG directories to a clean profile and generates a tiny init.lua that
#   installs LazyVerilog through lazy.nvim exactly like the README recommends.
#
# What is isolated:
#   XDG_CONFIG_HOME -> profile/config  (Neovim reads profile/config/nvim/init.lua)
#   XDG_DATA_HOME   -> profile/data    (lazy.nvim installs under profile/data/nvim)
#   XDG_STATE_HOME  -> profile/state   (shada/LSP state under profile/state/nvim)
#   XDG_CACHE_HOME  -> profile/cache   (cache under profile/cache/nvim)
#
# What is intentionally NOT done:
#   This script does not prepend this repository to 'runtimepath'.  Using the
#   local checkout would test developer state, not the documented installation
#   path.  By default lazy.nvim clones lazyverilog/LazyVerilog into the isolated
#   data directory, then LazyVerilog's own plugin code resolves/auto-installs
#   lazyverilog-lsp as described in README.md.  The README shows ft-based lazy
#   loading for normal users; this test script loads the plugin eagerly so a
#   first-run install is deterministic even when the filetype event has already
#   fired before lazy.nvim finishes cloning missing plugins.
#
# Usage:
#   tools/run_clean_nvim.sh [file-or-directory ...]
#
# Useful environment variables:
#   LAZYVERILOG_NVIM_PROFILE=/path/to/profile
#       Keep the isolated profile at a stable path instead of creating a fresh
#       /tmp directory.  Useful for repeatedly testing plugin updates.
#
#   LAZYVERILOG_LSP=/path/to/lazyverilog-lsp
#       Optional escape hatch for testing a local server binary while still
#       installing the Neovim plugin through lazy.nvim.  When unset, the README
#       default is used: PATH, plugin-managed binary, then auto-download.
#
#   LAZYVERILOG_KEEP_PROFILE=1
#       Do not delete the temporary profile on exit.  Useful for inspecting the
#       generated init.lua, lazy.nvim plugin checkout, logs, or downloaded LSP
#       binary after Neovim exits.
#
# Examples:
#   tools/run_clean_nvim.sh demo/memory_top.sv
#   LAZYVERILOG_KEEP_PROFILE=1 tools/run_clean_nvim.sh demo/tb_top.sv
#   LAZYVERILOG_LSP=build/lazyverilog-lsp tools/run_clean_nvim.sh demo/tb_top.sv

set -euo pipefail

if ! command -v nvim >/dev/null 2>&1; then
    echo "error: nvim is not on PATH" >&2
    exit 127
fi

# Use a unique temporary profile by default so every invocation is a clean
# first-install test.  Reusing a profile is opt-in because reused lazy.nvim data
# can mask first-install failures.  Set LAZYVERILOG_KEEP_PROFILE=1 when you want
# to inspect the installed plugin checkout after Neovim exits.
if [[ -n "${LAZYVERILOG_NVIM_PROFILE:-}" ]]; then
    profile_root=${LAZYVERILOG_NVIM_PROFILE}
    mkdir -p "${profile_root}"
    cleanup_profile=false
else
    profile_root=$(mktemp -d "${TMPDIR:-/tmp}/lazyverilog-nvim.XXXXXX")
    cleanup_profile=true
fi

cleanup() {
    if [[ "${cleanup_profile}" == true && "${LAZYVERILOG_KEEP_PROFILE:-0}" != 1 ]]; then
        rm -rf -- "${profile_root}"
    else
        echo "LazyVerilog clean Neovim profile kept at: ${profile_root}" >&2
    fi
}
trap cleanup EXIT

config_home="${profile_root}/config"
data_home="${profile_root}/data"
state_home="${profile_root}/state"
cache_home="${profile_root}/cache"

# Neovim appends /nvim to the XDG roots for stdpath("config"),
# stdpath("data"), stdpath("state"), and stdpath("cache").  The init.lua must
# therefore live at XDG_CONFIG_HOME/nvim/init.lua, not directly under
# XDG_CONFIG_HOME.  Putting it directly under config/ makes Neovim silently load
# the user's defaults/no config in a headless smoke test, which is exactly the
# class of false-positive this script is meant to avoid.
config_nvim="${config_home}/nvim"
data_nvim="${data_home}/nvim"
state_nvim="${state_home}/nvim"
cache_nvim="${cache_home}/nvim"
mkdir -p "${config_nvim}" "${data_nvim}" "${state_nvim}" "${cache_nvim}"

init_lua="${config_nvim}/init.lua"
cat > "${init_lua}" <<LUA
-- Generated by tools/run_clean_nvim.sh.
-- This init.lua intentionally avoids the user's normal Neovim configuration.
-- It bootstraps lazy.nvim, then installs LazyVerilog using the same plugin spec
-- shown in README.md.

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  local result = vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
  if vim.v.shell_error ~= 0 then
    error("failed to install lazy.nvim:\n" .. result)
  end
end
vim.opt.runtimepath:prepend(lazypath)

-- Keep all editor-generated files inside the isolated profile.  This prevents
-- swap/backup/undo files from leaking into the user's real Neovim directories
-- or into the LazyVerilog repository being tested.
vim.opt.directory = ${cache_nvim@Q} .. "/swap//"
vim.opt.backupdir = ${cache_nvim@Q} .. "/backup//"
vim.opt.undodir = ${state_nvim@Q} .. "/undo//"
vim.opt.undofile = true
vim.fn.mkdir(vim.opt.directory:get()[1], "p")
vim.fn.mkdir(vim.opt.backupdir:get()[1], "p")
vim.fn.mkdir(vim.opt.undodir:get()[1], "p")

-- This table is passed to require("lazyverilog").setup().  Keep it empty by
-- default so the plugin's documented command resolver runs:
--   1. lazyverilog-lsp on PATH
--   2. stdpath("data") .. "/lazyverilog/bin/lazyverilog-lsp"
--   3. release-binary auto-download
local lazyverilog_setup = {}

-- A clean Neovim profile intentionally does not load the user's normal
-- keymaps.  Mirror the LSP mappings from:
--   /home/user/dotfiles/nvim/.config/nvim/lua/plugins/lsp.lua
--
-- The dotfiles use Telescope for some picker-style LSP navigation, but this
-- clean profile intentionally uses only Neovim built-ins so it stays minimal
-- and tests LazyVerilog without extra plugin dependencies.
lazyverilog_setup.on_attach = function(_, bufnr)
  local function map(keys, func, desc, mode)
    mode = mode or "n"
    vim.keymap.set(mode, keys, func, { buffer = bufnr, desc = "LSP: " .. desc })
  end

  -- Rename the variable under your cursor.
  map("grn", vim.lsp.buf.rename, "[R]e[n]ame")

  -- Execute a code action in normal or visual mode.
  map("gra", vim.lsp.buf.code_action, "[G]oto Code [A]ction", { "n", "x" })

  -- Find references for the word under your cursor.
  map("grr", vim.lsp.buf.references, "[G]oto [R]eferences")

  -- Jump to implementation.
  map("gri", vim.lsp.buf.implementation, "[G]oto [I]mplementation")

  -- Jump to definition.  This overrides Vim's built-in text-only `gd`.
  map("gd", vim.lsp.buf.definition, "[G]oto [D]efinition")

  -- Jump to declaration.
  map("gD", vim.lsp.buf.declaration, "[G]oto [D]eclaration")

  -- List document symbols.
  map("gO", vim.lsp.buf.document_symbol, "Open Document Symbols")

  -- List workspace symbols.
  map("gW", vim.lsp.buf.workspace_symbol, "Open Workspace Symbols")

  -- Jump to type definition.
  map("grt", vim.lsp.buf.type_definition, "[G]oto [T]ype Definition")

  -- Toggle inlay hints.
  if vim.lsp.inlay_hint then
    map("<leader>th", function()
      vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = bufnr }), { bufnr = bufnr })
    end, "[T]oggle Inlay [H]ints")
  end
end
LUA

if [[ -n "${LAZYVERILOG_LSP:-}" ]]; then
    cat >> "${init_lua}" <<LUA
-- Explicit local-server override requested by LAZYVERILOG_LSP.  This is useful
-- for debugging a local C++ build while still testing plugin installation via
-- lazy.nvim.  It is not the default release-installation path.
lazyverilog_setup.cmd = ${LAZYVERILOG_LSP@Q}
LUA
fi

cat >> "${init_lua}" <<'LUA'
require("lazy").setup({
  spec = {
    {
      "lazyverilog/LazyVerilog",
      -- LazyVerilog keeps large RTL corpora as test submodules.  End users do
      -- not need those corpora when installing the Neovim plugin, so match the
      -- README and tell lazy.nvim not to fetch submodules.
      submodules = false,
      -- The README uses ft-based lazy loading for normal editing:
      --   ft = { "systemverilog", "verilog" }
      -- A clean installation test should be stricter: install and load the
      -- plugin at startup so first-run failures are visible immediately and do
      -- not depend on Neovim's filetype detection timing.
      lazy = false,
      config = function()
        require("lazyverilog").setup(lazyverilog_setup)
      end,
    },
  },
  install = {
    missing = true,
  },
})

vim.api.nvim_create_user_command("LazyVerilogCleanInfo", function()
  print("clean profile config: " .. vim.env.XDG_CONFIG_HOME)
  print("clean profile data:   " .. vim.env.XDG_DATA_HOME)
  print("lazy.nvim root:       " .. vim.fn.stdpath("data") .. "/lazy")
  print("lazyverilog setup:    " .. vim.inspect(lazyverilog_setup))
end, {})
LUA

echo "Starting clean Neovim profile: ${profile_root}" >&2
echo "Generated init.lua: ${init_lua}" >&2
echo "LazyVerilog plugin install: lazy.nvim spec lazyverilog/LazyVerilog (eager clean-test load)" >&2
if [[ -n "${LAZYVERILOG_LSP:-}" ]]; then
    echo "LazyVerilog LSP override: ${LAZYVERILOG_LSP}" >&2
else
    echo "LazyVerilog LSP: README default resolver (PATH / managed binary / auto-download)" >&2
fi

XDG_CONFIG_HOME="${config_home}" \
XDG_DATA_HOME="${data_home}" \
XDG_STATE_HOME="${state_home}" \
XDG_CACHE_HOME="${cache_home}" \
nvim "$@"
